Audio Track Quantity: '3'
Encoder:    # found in profiles/defaultVideo.yml
Environment: Unix   # must be either Unix (includes macOS and Linux) or Windows 
Episode List Name: episode_list.csv          # always in Episode Output Directory
HandBrakeCLI Executible Location: ./HandBrake/HandBrakeCLI.exe
Episode Output Directory: Episodes
